name: Daily Commit Action

on:
  schedule:
    - cron: '10 3 * * *'  # Runs daily at 03:10 UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Modify file for 23f1000333@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date -u)" >> last-run.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "23f1000333@ds.study.iitm.ac.in"
          git add last-run.txt
          git commit -m "Daily commit at $(date -u)" || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
