name: Daily Commit Action

on:
  schedule:
    - cron: '5 5 * * *'  # Runs every day at 05:05 UTC
  workflow_dispatch:       # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Append timestamp for 23f1000333@ds.study.iitm.ac.in
        run: |
          echo "Run at $(date -u)" >> .github/commit-log.txt

      - name: Commit and push changes for 23f1000333@ds.study.iitm.ac.in
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "23f1000333@ds.study.iitm.ac.in"
          git add .github/commit-log.txt
          git commit -m "Auto commit from GitHub Action on $(date -u)" || echo "No changes"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
